### ISSUE TITLE
Open Stream for USB Scale

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#157]
The `Open Stream` button either does not seem to work out of the box with the Mettler Toledo scale, or the sample.html file is broken.

The sample.html gets stuck on `Waiting on device`.

Steps:
1. Claim device: vendor: `0x0EB8`, product: `0xF000`, device: `0x00`, endpoint: `0x81`
2. Click `Open Stream`
3. Observe `Waiting on device` message.

![image](https://cloud.githubusercontent.com/assets/6345473/12774248/009e2434-ca11-11e5-9470-f9eb253d2378.png)

**Comment by akberenz** [comment]
Have you tried closing and re-opening the stream?
And since I do not have this usb device, could you send me the QZ logs, and check if there are any errors in the browser's console?

**Comment by tresf** [comment]
> Have you tried closing and re-opening the stream?

Yes.  It closes fine and opens fine.  I went back and added steps to reproduce.  Please let me know if I'm doing something wrong.

> And since I do not have this usb device, could you send me the QZ logs, and check if there are any errors in the browser's console?

There were none, which is why I mentioned a possible bug with sample.html.  As I understand it, the Dymo should behave the same.  Can you confirm there are no issues with the Dymo?  If not, I'd be happy to place the software in debug, but it won't be until much later in the day.

**Comment by akberenz** [comment]
I can confirm the dymo does not have this issue.

**Comment by tresf** [comment]
This is the console log from the browser:

```
Established connection with QZ Tray on ws://localhost:8182
```

This is the console log from the IDE:

```
[DEBUG] 2016-02-03 21:48:33,269 @ qz.ws.PrintSocketClient:162
    Message: {"call":"usb.claimDevice","promise":{},"params":{"vendorId":"0x0EB8","productId":"0xF000","interface":"0x00"},"timestamp":1454554113266,"uid":"yhle49"}
[WARN] 2016-02-03 21:48:33,270 @ qz.ws.PrintSocketClient:198
    Bad signature on request
[INFO] 2016-02-03 21:48:34,457 @ qz.common.TrayManager:414
    Allowed localhost to claim a USB device
[DEBUG] 2016-02-03 21:48:41,943 @ qz.ws.PrintSocketClient:162
    Message: {"call":"usb.openStream","promise":{},"params":{"vendorId":"0x0EB8","productId":"0xF000","endpoint":"0x81","responseSize":"8","interval":"10"},"timestamp":1454554121941,"uid":"zaa521"}
[WARN] 2016-02-03 21:48:41,945 @ qz.ws.PrintSocketClient:198
    Bad signature on request
[INFO] 2016-02-03 21:48:43,929 @ qz.common.TrayManager:414
    Allowed localhost to use a USB device
```

I don't see any useful information, but that is the entirety of the information I have.

> I can confirm the dymo does not have this issue.

Can you please send me the steps you used and the output you received?  I may just be using the feature incorrectly.

**Comment by akberenz** [comment]
Fixed with 1dccc5dc160136f35f555539ff19decb77488dc8

**Comment by tresf** [comment]
This is still broken with format `0x0EB8`, although it seems to work with format `0eb8` (lowercase).

**Comment by akberenz** [comment]
97a006c39c60960578c71887451b878dcd6dc9f4
I would like to note that this is entirely a problem specific to the demo page. As I would hope developers would give their usb data stream panel a fixed id, instead of the device dependent way we are doing it.

**Comment by tresf** [comment]
> I would like to note that this is entirely a problem specific to the demo page. As I would hope developers would give their usb data stream panel a fixed id, instead of the device dependent way we are doing it.

Yes, sorry, I had made mention of the specificity to our `sample.html` to our client, but failed to mention that point in the bug report. :+1:
